/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    BezierCurve: THREE.Mesh
    BezierCurve_1: THREE.Mesh
    BezierCurve_2: THREE.Mesh
  }
  materials: {
    ['Material.008']: THREE.MeshStandardMaterial
    ['Brushed Metal']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
  }
}

export function Arm(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/arm.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[2.559, 1.88, -0.46]} rotation={[-0.227, 0, 0]} scale={1.004}>
        <mesh castShadow receiveShadow geometry={nodes.BezierCurve.geometry} material={materials['Material.008']} />
        <mesh castShadow receiveShadow geometry={nodes.BezierCurve_1.geometry} material={materials['Brushed Metal']} />
        <mesh castShadow receiveShadow geometry={nodes.BezierCurve_2.geometry} material={materials['Material.013']} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/arm.glb')
