/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    HAND: THREE.Mesh
  }
  materials: {
    ['Car Paint 9']: THREE.MeshPhysicalMaterial
  }
}

export function Hand(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/hand.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HAND.geometry}
        material={materials['Car Paint 9']}
        position={[3.203, 1.369, 1.183]}
        rotation={[0.044, 0.46, -0.453]}
        scale={0.335}
      />
    </group>
  )
}

useGLTF.preload('/glb/hand.glb')
