/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    HEAD: THREE.Mesh
    NECK: THREE.Mesh
    NECK_4: THREE.Mesh
    NECK_2: THREE.Mesh
    NECK_3: THREE.Mesh
    CHEST: THREE.Mesh
    SHOULDER: THREE.Mesh
    ARM: THREE.Mesh
    ARM_2: THREE.Mesh
    NECK_5: THREE.Mesh
    LEG_2: THREE.Mesh
    CHEST_CLOTHES: THREE.Mesh
    HEAD_2: THREE.Mesh
    ANKLE: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder003_1: THREE.Mesh
    FOOT: THREE.Mesh
    KNEE: THREE.Mesh
    LEG: THREE.Mesh
    CHEST_CLOTHES001: THREE.Mesh
    HEAD_SCREEN: THREE.Mesh
    HEAD_3: THREE.Mesh
    CHEST_CLOTHES002: THREE.Mesh
    LEG_JOINT: THREE.Mesh
    BODY_SCREW: THREE.Mesh
    HAND: THREE.Mesh
    HEAD_GLASS: THREE.Mesh
    BODY_GLASS: THREE.Mesh
    CHEST001: THREE.Mesh
    line1: THREE.Mesh
    line2: THREE.Mesh
    line4: THREE.Mesh
    line3: THREE.Mesh
    OSL: THREE.Mesh
  }
  materials: {
    ['Car Paint 9']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Car Paint 9.001']: THREE.MeshStandardMaterial
    ['Brushed Metal']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Car Paint 2']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Car Paint 8']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Crystal 3']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Crystal 10']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Car Paint 9.002']: THREE.MeshStandardMaterial
    ['Car Paint 6']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Scratched Plastic 6']: THREE.MeshStandardMaterial
    ['Car Paint 3']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/data/poster.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HEAD.geometry}
        material={materials['Car Paint 9']}
        position={[0, 4.544, -1.126]}
        rotation={[-0.208, 0, 0]}
        scale={1.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NECK.geometry}
        material={materials['Material.004']}
        position={[0, 3.328, -0.953]}
        rotation={[-0.114, 0, 0]}
        scale={[0.399, 0.269, 0.213]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NECK_4.geometry}
        material={materials['Material.012']}
        position={[0, 2.952, -0.911]}
        rotation={[-0.114, 0, 0]}
        scale={[0.249, 0.162, 0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NECK_2.geometry}
        material={materials['Material.010']}
        position={[0, 1.74, -0.771]}
        rotation={[-0.114, 0, 0]}
        scale={[0.114, 0.045, 0.18]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NECK_3.geometry}
        material={nodes.NECK_3.material}
        position={[0, 1.72, -0.639]}
        rotation={[-0.227, 0, 0]}
        scale={[0.114, 0.045, 0.18]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CHEST.geometry}
        material={materials['Car Paint 9.001']}
        position={[0.001, 1.515, -0.331]}
        rotation={[-0.227, 0, 0]}
        scale={1.565}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SHOULDER.geometry}
        material={materials['Brushed Metal']}
        position={[0, 1.529, -0.329]}
        rotation={[-0.227, 0, 0]}
        scale={1.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ARM.geometry}
        material={materials['Material.008']}
        position={[2.559, 1.88, -0.46]}
        rotation={[-0.227, 0, 0]}
        scale={1.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ARM_2.geometry}
        material={materials['Material.013']}
        position={[-2.843, -1.152, -0.002]}
        rotation={[0.049, 1.025, 0.794]}
        scale={1.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NECK_5.geometry}
        material={materials['Brushed Metal']}
        position={[0, 1.566, -0.329]}
        rotation={[-0.227, 0, 0]}
        scale={1.578}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LEG_2.geometry}
        material={materials['Car Paint 2']}
        scale={[0.339, 0.657, 0.339]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CHEST_CLOTHES.geometry}
        material={materials['Material.001']}
        position={[0, 1.529, -0.329]}
        rotation={[-0.227, 0, 0]}
        scale={1.578}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HEAD_2.geometry}
        material={materials['Material.007']}
        position={[0, 4.544, -1.126]}
        rotation={[-0.208, 0, 0]}
        scale={1.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ANKLE.geometry}
        material={nodes.ANKLE.material}
        position={[0.216, -0.134, 0.64]}
        rotation={[0.522, -0.097, -0.166]}
        scale={[0.458, 0.182, 0.458]}
      />
      <group position={[0.216, -0.134, 0.64]} rotation={[0.542, -0.1, -0.164]} scale={[0.972, 0.645, 0.645]}>
        <mesh castShadow receiveShadow geometry={nodes.Cylinder003.geometry} material={materials['Material.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Cylinder003_1.geometry} material={materials['Car Paint 9']} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FOOT.geometry}
        material={materials['Brushed Metal']}
        position={[0.216, -0.134, 0.64]}
        rotation={[-2.605, 0.1, 0.171]}
        scale={[1.004, 1.004, 0.937]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.KNEE.geometry}
        material={materials['Car Paint 8']}
        position={[-0.395, 0.259, 0.262]}
        rotation={[-1.039, 0.038, -0.159]}
        scale={0.41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LEG.geometry}
        material={materials['Material.011']}
        position={[-0.395, 0.259, 0.262]}
        rotation={[-1.01, 0.033, -0.166]}
        scale={[0.339, 0.626, 0.339]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CHEST_CLOTHES001.geometry}
        material={materials['Crystal 3']}
        position={[0, 1.529, -0.329]}
        rotation={[-0.227, 0, 0]}
        scale={1.578}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HEAD_SCREEN.geometry}
        material={materials.Material}
        position={[0, 4.544, -1.126]}
        rotation={[-0.208, 0, 0]}
        scale={1.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HEAD_3.geometry}
        material={materials['Material.009']}
        position={[0, 4.544, -1.126]}
        rotation={[-0.208, 0, 0]}
        scale={1.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CHEST_CLOTHES002.geometry}
        material={materials['Material.016']}
        position={[0, 1.529, -0.329]}
        rotation={[-0.227, 0, 0]}
        scale={1.578}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LEG_JOINT.geometry}
        material={materials['Brushed Metal']}
        position={[0, 1.529, -0.329]}
        rotation={[-0.227, 0, 0]}
        scale={1.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BODY_SCREW.geometry}
        material={materials['Crystal 10']}
        position={[0, 0.026, 0.018]}
        rotation={[-0.227, 0, 0]}
        scale={1.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HAND.geometry}
        material={materials['Car Paint 9']}
        position={[3.203, 1.369, 1.183]}
        rotation={[0.044, 0.46, -0.453]}
        scale={0.335}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HEAD_GLASS.geometry}
        material={materials['Material.003']}
        position={[0.026, 1.681, 0.13]}
        rotation={[0.035, 0, 0]}
        scale={[0.778, 0.902, 0.295]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BODY_GLASS.geometry}
        material={materials['Material.006']}
        position={[0.026, 1.681, 0.13]}
        rotation={[0.035, 0, 0]}
        scale={[0.778, 0.902, 0.295]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CHEST001.geometry}
        material={materials['Car Paint 9.002']}
        position={[0.001, 1.515, -0.331]}
        rotation={[-0.227, 0, 0]}
        scale={1.565}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.line1.geometry}
        material={materials['Car Paint 6']}
        position={[-5.779, 6.288, 1.596]}
        rotation={[0.004, 0.29, 1.489]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.line2.geometry}
        material={materials['Material.015']}
        position={[-2.928, 5.005, 0.168]}
        rotation={[0, 0, -1.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.line4.geometry}
        material={materials['Scratched Plastic 6']}
        position={[-2.797, 5.933, -0.652]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.line3.geometry}
        material={materials['Car Paint 3']}
        position={[-2.406, 5.26, 0.095]}
        rotation={[0, 0, -1.121]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.OSL.geometry}
        material={materials['Material.018']}
        position={[-0.018, 2.309, 0.066]}
        rotation={[1.565, -1.121, 0.094]}
        scale={0.049}
      />
    </group>
  )
}

useGLTF.preload('/data/poster.glb')
