/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    BezierCurve005: THREE.Mesh
    BezierCurve005_1: THREE.Mesh
    BezierCurve005_2: THREE.Mesh
    BezierCurve005_3: THREE.Mesh
  }
  materials: {
    ['Scratched Plastic 6']: THREE.MeshStandardMaterial
    ['Car Paint 6']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Car Paint 3']: THREE.MeshStandardMaterial
  }
}

export function Polls(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/polls.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-2.797, 5.933, -0.652]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve005.geometry}
          material={materials['Scratched Plastic 6']}
        />
        <mesh castShadow receiveShadow geometry={nodes.BezierCurve005_1.geometry} material={materials['Car Paint 6']} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve005_2.geometry}
          material={materials['Material.015']}
        />
        <mesh castShadow receiveShadow geometry={nodes.BezierCurve005_3.geometry} material={materials['Car Paint 3']} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/polls.glb')
